### PR TITLE
Auto fetching data when compiling

### PR DESCRIPTION
**Pull request by Boris-rnd**
Automatically fetchs data from website so you don't to every day !
+ This repo isn't really active so...

Maybe we should still have a offline version ?

### CODE REVIEW

**Comment by mkroening** [comment]
I am not sure if it would be good to decouple the crate version from the used database. Why not update the submodule every so often when necessary?

**Comment by lienching** [comment]
I think this is a good approach that eliminate the need of frequent maintenance.
However, I think we should consider to have multiple ways/sources to fetch the latest pci-ids list.

**Comment by Boris-rnd** [comment]
> I think this is a good approach that eliminate the need of frequent maintenance. However, I think we should consider to have multiple ways/sources to fetch the latest pci-ids list.

I'm okay with that but isn't the website pci-ids.ucw.cz the main repo for pci ids ?
+ I've just seen that we shouldn't download the file from pci-ids.ucw.cz but from there github repo.
A github action would work ?

**Comment by lienching** [comment]
Hi @Sxmourai ,
Can you change the URL that fetch pci-ids list to `https://raw.githubusercontent.com/pciutils/pciids/master/pci.ids` ? And run `cargo fmt` to format the code?

**Comment by Boris-rnd** [comment]
No because on githubusercontent it will be your un updated version, whereas https://pci-ids.ucw.cz/v2.2/pci.ids will be the last version... Tho it's v2.2 in url so we might have to change that...

**Comment by Boris-rnd** [comment]
On their website:
Automated downloads: If you download the snapshots automatically, please put the name of your program in the User-Agent HTTP header and tell us about it. Please cache the files responsively. Please use compression (by either downloading the compressed version or requesting Accept-Encoding: gzip in HTTP headers). Excessive downloads (hundrends of requests per day or more) could lead to a ban on your IP addresses.

We should probably do that ?
Or do caching on github ?

**Comment by lienching** [comment]
https://raw.githubusercontent.com/pciutils/pciids/master/pci.ids   <-- This will always point to the latest cached pci.ids

Can you change the code to first fetch the modification time from both sites (official pci.ids and github cached pci.ids), and if the official pci.ids is newer then the github cached pci.ids, then proceed the download process to get the latest pci.ids from the official site. Otherwise, get the list from github.

**Comment by Boris-rnd** [comment]
Docs.rs doesn't have internet access to build the images, so now it should compile and get published without problems too

**Pull request merged**
